#!/bin/sh

test -e $SNAP_DATA/daemon_arguments || cp $SNAP/etc/juju-introspection-proxy/daemon_arguments.example $SNAP_DATA/daemon_arguments

. $SNAP_DATA/daemon_arguments
exec $SNAP/bin/juju-introspection-proxy $ARGS
